# EightPoints GuzzleBundle
# A full list of configuration options can be found here:
# https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/configuration-reference.md
eight_points_guzzle:
    logging: true
    clients:
        open_weather_api:
            base_url: "https://api.openweathermap.org"
            class: App\Client\OpenWeatherClient

            options:
                timeout: 30

                # set to false to disable throwing exceptions on an HTTP protocol errors (4xx and 5xx responses)
                http_errors: true

                headers:
                    User-Agent: "Pauliaus Loxone"
                    Accept: "application/json"

            plugin: ~
        sun_api:
            base_url: "https://api.sunrise-sunset.org/"
            class: App\Client\SunClient

            options:
                timeout: 30

                http_errors: true

                headers:
                    User-Agent: "Pauliaus Loxone"
                    Accept: "application/json"
            plugin: ~

        meteo_api:
            # Write here the host where to do requests
            base_url: "https://api.meteo.lt/"
            class: App\Client\MeteoClient

            options:
                # timeout in seconds
                timeout: 30

                http_errors: true
                headers:
                    User-Agent: "Pauliaus Loxone"
                    Accept: "application/json"
            plugin: ~