monolog:
    handlers:
        weather:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/weather.%kernel.environment%.log'
            max_files: 10
            channels: ["weather"]
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10
            channels: ["!event", "!weather"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
